/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Conexiones.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Andres
 */

public class frmMiCRUD extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();

   public frmMiCRUD() {
        initComponents();
        mostrarDatos();
    }
   
   public frmMiCRUD(String lblMensaje){
    initComponents();
    lblMensaje = "Nombre del Alumno: ";
    this.jLabel5.setText(lblMensaje);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNOMBREALUM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAPELLIDO = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCURSO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCALIFICACION = new javax.swing.JTextField();
        cmdGuardar = new javax.swing.JButton();
        cmdEditar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaAlumnos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNOMBREALUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMBREALUMActionPerformed(evt);
            }
        });

        jLabel1.setText("Apelldios del alumno:");

        txtAPELLIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAPELLIDOActionPerformed(evt);
            }
        });

        jLabel2.setText("Curso");

        jLabel3.setText("Calificacion:");

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });

        cmdEditar.setText("Editar");
        cmdEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditarActionPerformed(evt);
            }
        });

        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });

        cmdNuevo.setText("Nuevo");
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });

        jtablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablaAlumnos);

        jLabel4.setText("ID: ");

        id.setEditable(false);

        jLabel5.setText("Nombre del Alumno: ");

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNOMBREALUM, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(txtAPELLIDO, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(txtCURSO, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(txtCALIFICACION, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(cmdEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdNuevo)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(txtNOMBREALUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCURSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCALIFICACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdGuardar)
                            .addComponent(cmdEditar)
                            .addComponent(cmdEliminar)
                            .addComponent(cmdNuevo)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNOMBREALUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMBREALUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMBREALUMActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        // TODO add your handling code here:
        insertarDatos();
        mostrarDatos();
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditarActionPerformed
        // TODO add your handling code here:
        Editar();
        mostrarDatos();
    }//GEN-LAST:event_cmdEditarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        
        eliminar(id.getText());
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed
            limpiarDatos();
    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void txtAPELLIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAPELLIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAPELLIDOActionPerformed

    private void jtablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaAlumnosMouseClicked
        // TODO add your handling code here:
        int filaSelect = jtablaAlumnos.rowAtPoint(evt.getPoint());
        String txtid = (String) jtablaAlumnos.getValueAt(filaSelect, 0);
        id.setText(txtid);
        txtNOMBREALUM.setText(jtablaAlumnos.getValueAt(filaSelect,1).toString());
        txtAPELLIDO.setText(jtablaAlumnos.getValueAt(filaSelect,2).toString());
        txtCURSO.setText(jtablaAlumnos.getValueAt(filaSelect,3).toString());
        txtCALIFICACION.setText(jtablaAlumnos.getValueAt(filaSelect,4).toString());
    }//GEN-LAST:event_jtablaAlumnosMouseClicked

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed

            // bton salir 
            
            System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    public void limpiarDatos(){
        txtNOMBREALUM.setText("");
        txtAPELLIDO.setText("");
        txtCURSO.setText("");
        txtCALIFICACION.setText("");
    }
    
    public void Editar(){
        try{
            
            String SQL = "update alumnos set nombre =?, apellido =?, materia =?, calificacion =? where idalumnos =?";
            
            int filaSelect = jtablaAlumnos.getSelectedRow();
            String txtid = (String) jtablaAlumnos.getValueAt(filaSelect, 0);
            id.setText(txtid);
            PreparedStatement pst = con.prepareStatement(SQL);
            
            pst.setString(1, txtNOMBREALUM.getText());
            pst.setString(2, txtAPELLIDO.getText());
            pst.setString(3, txtCURSO.getText());
            pst.setString(4, txtCALIFICACION.getText());
            pst.setString(5, id.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Registro actualizado exitosamente");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocurrio un error inseperado al hacer el registro");
        }
        
       
    }
   /* public void insertarDatos(){
        try{
        String SQL = "insert into alumnos (nombres, apellidos, materia, calificacion) values (?, ?, ?, ?)";
        PreparedStatement pst = con.PreparedStatement;    
        
        }catch{
            
        }
        
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMiCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMiCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMiCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMiCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMiCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton cmdEditar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtablaAlumnos;
    private javax.swing.JTextField txtAPELLIDO;
    private javax.swing.JTextField txtCALIFICACION;
    private javax.swing.JTextField txtCURSO;
    private javax.swing.JTextField txtNOMBREALUM;
    // End of variables declaration//GEN-END:variables

    private void insertarDatos() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        try{
            String SQL ="insert into alumnos (nombre, apellido, materia, calificacion) values(?,?,?,?)";
            
            PreparedStatement pst = con.prepareStatement(SQL);
            
            pst.setString(1, txtNOMBREALUM.getText());
            pst.setString(2, txtAPELLIDO.getText());
            pst.setString(3, txtCURSO.getText());
            pst.setString(4, txtCALIFICACION.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Registro exitoso");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al ingresar el registro");
        }
    }
    
    public void mostrarDatos(){
        String[] titulos = {"ID","nombre","apellido","materia", "calificacion"};
        String[] registros = new String[10];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        String sql = "select * from alumnos";

        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                registros[0] = rs.getString("idalumnos");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("apellido");
                registros[3] = rs.getString("materia");
                registros[4] = rs.getString("calificacion");
                
                modelo.addRow(registros);
                
            }
            jtablaAlumnos.setModel(modelo);
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Error al mostrar lo datos"+ e.getMessage());
        }
                
    }
    
    public void eliminar(String txtid){
        
    try{
    
        String SQL = " DELETE FROM  alumnos where idalumnos = ?";
        
        //int filaSelect = jtablaAlumnos.getSelectedRow();
        
        
        PreparedStatement pst = con.prepareStatement(SQL);
        
        pst.setString(1, id.getText());  
        pst.execute();
        
        JOptionPane.showMessageDialog(null,"Registro eliminar Exitosamente");
        mostrarDatos();
    }catch (Exception e)
    {
        JOptionPane.showMessageDialog(null,"Error al Registrar");
    }
    }
}
